#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : base.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jul 20 00:47:11 +0800 2022
# SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_10 processing_system7_vip_v1_0_12 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 v_vid_in_axi4s_v4_0_9 lib_pkg_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_iic_v2_1_0 axi_intc_v4_1_15 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_24 fifo_generator_v13_2_5 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_26 axi_vdma_v6_3_12 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_23 axi_crossbar_v2_1_25 v_tc_v6_1_13 v_axi4s_vid_out_v4_0_12 v_tc_v6_2_2 xlconcat_v2_1_4 axi_protocol_converter_v2_1_24)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2021.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/0980/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_processing_system7_0_0/sim/base_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_rst_ps7_0_100M_0/sim/base_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ipshared/31a1/src/asyn_rst_syn.v" \
    "$ref_dir/../../../bd/base/ipshared/31a1/src/dvi_encoder.v" \
    "$ref_dir/../../../bd/base/ipshared/31a1/src/serializer_10_to_1.v" \
    "$ref_dir/../../../bd/base/ipshared/31a1/src/dvi_transmitter_top.v" \
    "$ref_dir/../../../bd/base/ip/base_DVI_Transmitter_0_0/sim/base_DVI_Transmitter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_v_vid_in_axi4s_2_0/sim/base_v_vid_in_axi4s_2_0.v" \
    "$ref_dir/../../../bd/base/ip/base_v_vid_in_axi4s_1_0/sim/base_v_vid_in_axi4s_1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_v_vid_in_axi4s_0_0/sim/base_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_rst_ps7_0_50M_0/sim/base_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_1_0 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/68d2/hdl/axi_iic_v2_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_iic_0/sim/base_axi_iic_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/47b8/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_intc_0_0/sim/base_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_0/sim/bd_60ff_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_1/sim/bd_60ff_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_2/sim/bd_60ff_arsw_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_3/sim/bd_60ff_rsw_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_4/sim/bd_60ff_awsw_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_5/sim/bd_60ff_wsw_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_6/sim/bd_60ff_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_7/sim/bd_60ff_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_8/sim/bd_60ff_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_9/sim/bd_60ff_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_10/sim/bd_60ff_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_11/sim/bd_60ff_sarn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_12/sim/bd_60ff_srn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_13/sim/bd_60ff_s01mmu_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_14/sim/bd_60ff_s01tr_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_15/sim/bd_60ff_s01sic_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_16/sim/bd_60ff_s01a2s_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_17/sim/bd_60ff_sawn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_18/sim/bd_60ff_swn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_19/sim/bd_60ff_sbn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_20/sim/bd_60ff_s02mmu_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_21/sim/bd_60ff_s02tr_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_22/sim/bd_60ff_s02sic_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_23/sim/bd_60ff_s02a2s_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_24/sim/bd_60ff_sarn_1.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_25/sim/bd_60ff_srn_1.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_26/sim/bd_60ff_s03mmu_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_27/sim/bd_60ff_s03tr_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_28/sim/bd_60ff_s03sic_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_29/sim/bd_60ff_s03a2s_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_30/sim/bd_60ff_sawn_1.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_31/sim/bd_60ff_swn_1.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_32/sim/bd_60ff_sbn_1.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_33/sim/bd_60ff_s04mmu_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_34/sim/bd_60ff_s04tr_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_35/sim/bd_60ff_s04sic_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_36/sim/bd_60ff_s04a2s_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_37/sim/bd_60ff_sarn_2.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_38/sim/bd_60ff_srn_2.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_39/sim/bd_60ff_s05mmu_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_40/sim/bd_60ff_s05tr_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_41/sim/bd_60ff_s05sic_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_42/sim/bd_60ff_s05a2s_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_43/sim/bd_60ff_sawn_2.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_44/sim/bd_60ff_swn_2.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_45/sim/bd_60ff_sbn_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_46/sim/bd_60ff_m00s2a_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_47/sim/bd_60ff_m00arn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_48/sim/bd_60ff_m00rn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_49/sim/bd_60ff_m00awn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_50/sim/bd_60ff_m00wn_0.sv" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_51/sim/bd_60ff_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/ip/ip_52/sim/bd_60ff_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/bd_0/sim/bd_60ff.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/8f68/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axi_smc_0/sim/base_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_26 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/1e21/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_12 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_vdma_0_0/sim/base_axi_vdma_0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_axi_vdma_1_0/sim/base_axi_vdma_1_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_axi_vdma_2_0/sim/base_axi_vdma_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_clk_wiz_1_0/base_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/base/ip/base_clk_wiz_1_0/base_clk_wiz_1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_cmos_pwdn_0/sim/base_cmos_pwdn_0.v" \
    "$ref_dir/../../../bd/base/ip/base_cmos_rst_n_0/sim/base_cmos_rst_n_0.v" \
    "$ref_dir/../../../bd/base/ip/base_lcd_bl_0/sim/base_lcd_bl_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/94ec/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/3917/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_xbar_0/sim/base_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/2f8d/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_v_axi4s_vid_out_0_0/sim/base_v_axi4s_vid_out_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_v_axi4s_vid_out_1_0/sim/base_v_axi4s_vid_out_1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_v_axi4s_vid_out_2_0/sim/base_v_axi4s_vid_out_2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/7f10/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_v_tc_0_0/sim/base_v_tc_0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_v_tc_1_0/sim/base_v_tc_1_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_v_tc_2_0/sim/base_v_tc_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_xlconcat_0_0/sim/base_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/base/ipshared/0912/hdl/dvp_raw_timing_colorbar.v" \
    "$ref_dir/../../../bd/base/ipshared/0912/hdl/xil_camif_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/base/ipshared/0912/hdl/xil_camif_v1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_xil_camif_0_0/sim/base_xil_camif_0_0.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_2dnr.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_blc.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_bnr.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_ccm.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_csc.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_demosaic.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_dgain.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_dpc.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_ee.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_gamma.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_stat_ae.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_stat_awb.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_top.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_utils.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/isp_lite/isp_wb.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/xil_isp_lite_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/base/ipshared/9ff0/hdl/xil_isp_lite_v1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_xil_isp_lite_0_0/sim/base_xil_isp_lite_0_0.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_crop.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_dscale.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_hist_equ.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_osd.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_sobel.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_top.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_yuv2rgb.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/vip/vip_yuv444to422.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/xil_vip_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/base/ipshared/60e6/hdl/xil_vip_v1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_xil_vip_0_0/sim/base_xil_vip_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_xil_vip_1_0/sim/base_xil_vip_1_0.v" \
    "$ref_dir/../../../bd/base/sim/base.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6e0d/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/f42d/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/66f2/hdl" +incdir+"$ref_dir/../../../../zynq_cam_isp_demo.gen/sources_1/bd/base/ipshared/6dcf" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
