# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Work/fpga/zynq_cam_isp_demo/zynq_cam_isp_demo.srcs/sources_1/bd/base/ip/base_xil_vip_1_0/base_xil_vip_1_0.xci
# IP: The module: 'base_xil_vip_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/fpga/zynq_cam_isp_demo/zynq_cam_isp_demo.gen/sources_1/bd/base/ip/base_xil_vip_1_0/hdl/xil_vip_v1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xil_vip_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Work/fpga/zynq_cam_isp_demo/zynq_cam_isp_demo.srcs/sources_1/bd/base/ip/base_xil_vip_1_0/base_xil_vip_1_0.xci
# IP: The module: 'base_xil_vip_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/fpga/zynq_cam_isp_demo/zynq_cam_isp_demo.gen/sources_1/bd/base/ip/base_xil_vip_1_0/hdl/xil_vip_v1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xil_vip_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
