// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module h264_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_empty_n,
        img_read,
        bytePlanes_01_din,
        bytePlanes_01_full_n,
        bytePlanes_01_write,
        bytePlanes_12_din,
        bytePlanes_12_full_n,
        bytePlanes_12_write,
        Height_dout,
        Height_empty_n,
        Height_read,
        p_read,
        p_read1,
        WidthInBytes_c_din,
        WidthInBytes_c_full_n,
        WidthInBytes_c_write,
        height_c_din,
        height_c_full_n,
        height_c_write,
        video_format_c_din,
        video_format_c_full_n,
        video_format_c_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input   img_empty_n;
output   img_read;
output  [63:0] bytePlanes_01_din;
input   bytePlanes_01_full_n;
output   bytePlanes_01_write;
output  [63:0] bytePlanes_12_din;
input   bytePlanes_12_full_n;
output   bytePlanes_12_write;
input  [9:0] Height_dout;
input   Height_empty_n;
output   Height_read;
input  [13:0] p_read;
input  [5:0] p_read1;
output  [13:0] WidthInBytes_c_din;
input   WidthInBytes_c_full_n;
output   WidthInBytes_c_write;
output  [9:0] height_c_din;
input   height_c_full_n;
output   height_c_write;
output  [5:0] video_format_c_din;
input   video_format_c_full_n;
output   video_format_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg bytePlanes_01_write;
reg bytePlanes_12_write;
reg Height_read;
reg WidthInBytes_c_write;
reg height_c_write;
reg video_format_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    WidthInBytes_c_blk_n;
reg    height_c_blk_n;
reg    video_format_c_blk_n;
wire   [5:0] p_read_3_read_fu_146_p2;
reg   [9:0] Height_read_reg_403;
wire   [11:0] trunc_ln470_2_fu_227_p4;
reg   [11:0] trunc_ln470_2_reg_427;
wire   [0:0] icmp_ln473_fu_241_p2;
reg   [0:0] icmp_ln473_reg_432;
wire   [11:0] sub25_fu_255_p2;
reg   [11:0] sub25_reg_437;
wire   [0:0] brmerge30_not_fu_261_p2;
reg   [0:0] brmerge30_not_reg_442;
wire   [0:0] icmp_ln488_fu_267_p2;
reg   [0:0] icmp_ln488_reg_447;
wire   [0:0] icmp_ln488_1_fu_283_p2;
reg   [0:0] icmp_ln488_1_reg_452;
wire   [0:0] icmp_ln488_2_fu_289_p2;
reg   [0:0] icmp_ln488_2_reg_457;
wire   [0:0] icmp_ln488_3_fu_305_p2;
reg   [0:0] icmp_ln488_3_reg_462;
wire   [0:0] icmp_ln488_4_fu_311_p2;
reg   [0:0] icmp_ln488_4_reg_467;
wire   [0:0] icmp_ln488_5_fu_317_p2;
reg   [0:0] icmp_ln488_5_reg_472;
wire   [0:0] icmp_ln488_6_fu_323_p2;
reg   [0:0] icmp_ln488_6_reg_477;
wire   [0:0] demorgan_fu_360_p2;
reg   [0:0] demorgan_reg_491;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln479_fu_341_p2;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_01_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_01_write;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_12_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_12_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out1;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out1_ap_vld;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [9:0] y_fu_134;
wire   [9:0] y_2_fu_346_p2;
reg    ap_block_state1;
reg   [7:0] empty_fu_138;
reg   [7:0] empty_102_fu_142;
wire   [14:0] zext_ln470_fu_217_p1;
wire   [14:0] add_ln470_fu_221_p2;
wire   [2:0] remainPix_fu_213_p1;
wire   [3:0] zext_ln472_fu_237_p1;
wire   [3:0] remainPix_1_fu_247_p3;
wire   [2:0] tmp_fu_273_p4;
wire   [1:0] tmp_2_fu_295_p4;
wire   [0:0] trunc_ln479_fu_337_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start_reg = 1'b0;
end

h264_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_ready),
    .img_dout(img_dout),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_img_read),
    .empty_47(empty_102_fu_142),
    .empty(empty_fu_138),
    .trunc_ln470_2(trunc_ln470_2_reg_427),
    .bytePlanes_01_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_01_din),
    .bytePlanes_01_full_n(bytePlanes_01_full_n),
    .bytePlanes_01_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_01_write),
    .demorgan(demorgan_reg_491),
    .icmp_ln473(icmp_ln473_reg_432),
    .icmp_ln488_6(icmp_ln488_6_reg_477),
    .icmp_ln488_5(icmp_ln488_5_reg_472),
    .icmp_ln488_4(icmp_ln488_4_reg_467),
    .icmp_ln488_3(icmp_ln488_3_reg_462),
    .icmp_ln488_2(icmp_ln488_2_reg_457),
    .icmp_ln488_1(icmp_ln488_1_reg_452),
    .sub25_cast21(sub25_reg_437),
    .icmp_ln488(icmp_ln488_reg_447),
    .bytePlanes_12_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_12_din),
    .bytePlanes_12_full_n(bytePlanes_12_full_n),
    .bytePlanes_12_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_12_write),
    .p_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out),
    .p_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out_ap_vld),
    .p_out1(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out1),
    .p_out1_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln479_fu_341_p2 == 1'd1) | (~(p_read_3_read_fu_146_p2 == 6'd18) & ~(p_read_3_read_fu_146_p2 == 6'd19))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (((p_read_3_read_fu_146_p2 == 6'd18) & (icmp_ln479_fu_341_p2 == 1'd0)) | ((p_read_3_read_fu_146_p2 == 6'd19) & (icmp_ln479_fu_341_p2 == 1'd0))))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & ((p_read_3_read_fu_146_p2 == 6'd18) | (p_read_3_read_fu_146_p2 == 6'd19)))) begin
        y_fu_134 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (((p_read_3_read_fu_146_p2 == 6'd18) & (icmp_ln479_fu_341_p2 == 1'd0)) | ((p_read_3_read_fu_146_p2 == 6'd19) & (icmp_ln479_fu_341_p2 == 1'd0))))) begin
        y_fu_134 <= y_2_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Height_read_reg_403 <= Height_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ((p_read_3_read_fu_146_p2 == 6'd18) | (p_read_3_read_fu_146_p2 == 6'd19)))) begin
        brmerge30_not_reg_442 <= brmerge30_not_fu_261_p2;
        icmp_ln473_reg_432 <= icmp_ln473_fu_241_p2;
        icmp_ln488_1_reg_452 <= icmp_ln488_1_fu_283_p2;
        icmp_ln488_2_reg_457 <= icmp_ln488_2_fu_289_p2;
        icmp_ln488_3_reg_462 <= icmp_ln488_3_fu_305_p2;
        icmp_ln488_4_reg_467 <= icmp_ln488_4_fu_311_p2;
        icmp_ln488_5_reg_472 <= icmp_ln488_5_fu_317_p2;
        icmp_ln488_6_reg_477 <= icmp_ln488_6_fu_323_p2;
        icmp_ln488_reg_447 <= icmp_ln488_fu_267_p2;
        sub25_reg_437 <= sub25_fu_255_p2;
        trunc_ln470_2_reg_427 <= {{add_ln470_fu_221_p2[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (((p_read_3_read_fu_146_p2 == 6'd18) & (icmp_ln479_fu_341_p2 == 1'd0)) | ((p_read_3_read_fu_146_p2 == 6'd19) & (icmp_ln479_fu_341_p2 == 1'd0))))) begin
        demorgan_reg_491 <= demorgan_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_102_fu_142 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out;
        empty_fu_138 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_p_out1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_blk_n = WidthInBytes_c_full_n;
    end else begin
        WidthInBytes_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_write = 1'b1;
    end else begin
        WidthInBytes_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln479_fu_341_p2 == 1'd1) | (~(p_read_3_read_fu_146_p2 == 6'd18) & ~(p_read_3_read_fu_146_p2 == 6'd19))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln479_fu_341_p2 == 1'd1) | (~(p_read_3_read_fu_146_p2 == 6'd18) & ~(p_read_3_read_fu_146_p2 == 6'd19))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bytePlanes_01_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_01_write;
    end else begin
        bytePlanes_01_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bytePlanes_12_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_12_write;
    end else begin
        bytePlanes_12_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_blk_n = height_c_full_n;
    end else begin
        height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_write = 1'b1;
    end else begin
        height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_img_read;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_blk_n = video_format_c_full_n;
    end else begin
        video_format_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_write = 1'b1;
    end else begin
        video_format_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln479_fu_341_p2 == 1'd1) | (~(p_read_3_read_fu_146_p2 == 6'd18) & ~(p_read_3_read_fu_146_p2 == 6'd19))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign WidthInBytes_c_din = p_read;

assign add_ln470_fu_221_p2 = (zext_ln470_fu_217_p1 + 15'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1));
end

assign brmerge30_not_fu_261_p2 = ((p_read1 == 6'd19) ? 1'b1 : 1'b0);

assign bytePlanes_01_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_01_din;

assign bytePlanes_12_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_bytePlanes_12_din;

assign demorgan_fu_360_p2 = (trunc_ln479_fu_337_p1 & brmerge30_not_reg_442);

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_483_1_fu_188_ap_start_reg;

assign height_c_din = Height_dout;

assign icmp_ln473_fu_241_p2 = ((remainPix_fu_213_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln479_fu_341_p2 = ((y_fu_134 == Height_read_reg_403) ? 1'b1 : 1'b0);

assign icmp_ln488_1_fu_283_p2 = ((tmp_fu_273_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln488_2_fu_289_p2 = ((remainPix_1_fu_247_p3 > 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln488_3_fu_305_p2 = ((tmp_2_fu_295_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln488_4_fu_311_p2 = ((remainPix_1_fu_247_p3 > 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln488_5_fu_317_p2 = ((remainPix_1_fu_247_p3 > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln488_6_fu_323_p2 = ((remainPix_1_fu_247_p3 > 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln488_fu_267_p2 = ((remainPix_1_fu_247_p3 != 4'd0) ? 1'b1 : 1'b0);

assign p_read_3_read_fu_146_p2 = p_read1;

assign remainPix_1_fu_247_p3 = ((icmp_ln473_fu_241_p2[0:0] == 1'b1) ? 4'd8 : zext_ln472_fu_237_p1);

assign remainPix_fu_213_p1 = p_read[2:0];

assign sub25_fu_255_p2 = ($signed(trunc_ln470_2_fu_227_p4) + $signed(12'd4095));

assign tmp_2_fu_295_p4 = {{remainPix_1_fu_247_p3[3:2]}};

assign tmp_fu_273_p4 = {{remainPix_1_fu_247_p3[3:1]}};

assign trunc_ln470_2_fu_227_p4 = {{add_ln470_fu_221_p2[14:3]}};

assign trunc_ln479_fu_337_p1 = y_fu_134[0:0];

assign video_format_c_din = p_read1;

assign y_2_fu_346_p2 = (y_fu_134 + 10'd1);

assign zext_ln470_fu_217_p1 = p_read;

assign zext_ln472_fu_237_p1 = remainPix_fu_213_p1;

endmodule //h264_v_frmbuf_wr_0_0_MultiPixStream2Bytes
