// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module h264_v_frmbuf_wr_0_0_FrmbufWrHlsDataFlow (
        s_axis_video_TDATA,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        m_axi_mm_video_AWVALID,
        m_axi_mm_video_AWREADY,
        m_axi_mm_video_AWADDR,
        m_axi_mm_video_AWID,
        m_axi_mm_video_AWLEN,
        m_axi_mm_video_AWSIZE,
        m_axi_mm_video_AWBURST,
        m_axi_mm_video_AWLOCK,
        m_axi_mm_video_AWCACHE,
        m_axi_mm_video_AWPROT,
        m_axi_mm_video_AWQOS,
        m_axi_mm_video_AWREGION,
        m_axi_mm_video_AWUSER,
        m_axi_mm_video_WVALID,
        m_axi_mm_video_WREADY,
        m_axi_mm_video_WDATA,
        m_axi_mm_video_WSTRB,
        m_axi_mm_video_WLAST,
        m_axi_mm_video_WID,
        m_axi_mm_video_WUSER,
        m_axi_mm_video_ARVALID,
        m_axi_mm_video_ARREADY,
        m_axi_mm_video_ARADDR,
        m_axi_mm_video_ARID,
        m_axi_mm_video_ARLEN,
        m_axi_mm_video_ARSIZE,
        m_axi_mm_video_ARBURST,
        m_axi_mm_video_ARLOCK,
        m_axi_mm_video_ARCACHE,
        m_axi_mm_video_ARPROT,
        m_axi_mm_video_ARQOS,
        m_axi_mm_video_ARREGION,
        m_axi_mm_video_ARUSER,
        m_axi_mm_video_RVALID,
        m_axi_mm_video_RREADY,
        m_axi_mm_video_RDATA,
        m_axi_mm_video_RLAST,
        m_axi_mm_video_RID,
        m_axi_mm_video_RUSER,
        m_axi_mm_video_RRESP,
        m_axi_mm_video_BVALID,
        m_axi_mm_video_BREADY,
        m_axi_mm_video_BRESP,
        m_axi_mm_video_BID,
        m_axi_mm_video_BUSER,
        HwReg_frm_buffer,
        HwReg_frm_buffer2,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read14,
        p_read25,
        ap_clk,
        ap_rst,
        HwReg_frm_buffer_ap_vld,
        HwReg_frm_buffer2_ap_vld,
        p_read_ap_vld,
        p_read14_ap_vld,
        p_read25_ap_vld,
        ap_start,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        p_read3_ap_vld,
        p_read2_ap_vld,
        p_read1_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [23:0] s_axis_video_TDATA;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output   m_axi_mm_video_AWVALID;
input   m_axi_mm_video_AWREADY;
output  [31:0] m_axi_mm_video_AWADDR;
output  [0:0] m_axi_mm_video_AWID;
output  [31:0] m_axi_mm_video_AWLEN;
output  [2:0] m_axi_mm_video_AWSIZE;
output  [1:0] m_axi_mm_video_AWBURST;
output  [1:0] m_axi_mm_video_AWLOCK;
output  [3:0] m_axi_mm_video_AWCACHE;
output  [2:0] m_axi_mm_video_AWPROT;
output  [3:0] m_axi_mm_video_AWQOS;
output  [3:0] m_axi_mm_video_AWREGION;
output  [0:0] m_axi_mm_video_AWUSER;
output   m_axi_mm_video_WVALID;
input   m_axi_mm_video_WREADY;
output  [63:0] m_axi_mm_video_WDATA;
output  [7:0] m_axi_mm_video_WSTRB;
output   m_axi_mm_video_WLAST;
output  [0:0] m_axi_mm_video_WID;
output  [0:0] m_axi_mm_video_WUSER;
output   m_axi_mm_video_ARVALID;
input   m_axi_mm_video_ARREADY;
output  [31:0] m_axi_mm_video_ARADDR;
output  [0:0] m_axi_mm_video_ARID;
output  [31:0] m_axi_mm_video_ARLEN;
output  [2:0] m_axi_mm_video_ARSIZE;
output  [1:0] m_axi_mm_video_ARBURST;
output  [1:0] m_axi_mm_video_ARLOCK;
output  [3:0] m_axi_mm_video_ARCACHE;
output  [2:0] m_axi_mm_video_ARPROT;
output  [3:0] m_axi_mm_video_ARQOS;
output  [3:0] m_axi_mm_video_ARREGION;
output  [0:0] m_axi_mm_video_ARUSER;
input   m_axi_mm_video_RVALID;
output   m_axi_mm_video_RREADY;
input  [63:0] m_axi_mm_video_RDATA;
input   m_axi_mm_video_RLAST;
input  [0:0] m_axi_mm_video_RID;
input  [0:0] m_axi_mm_video_RUSER;
input  [1:0] m_axi_mm_video_RRESP;
input   m_axi_mm_video_BVALID;
output   m_axi_mm_video_BREADY;
input  [1:0] m_axi_mm_video_BRESP;
input  [0:0] m_axi_mm_video_BID;
input  [0:0] m_axi_mm_video_BUSER;
input  [31:0] HwReg_frm_buffer;
input  [31:0] HwReg_frm_buffer2;
input  [13:0] p_read;
input  [2:0] p_read1;
input  [10:0] p_read2;
input  [9:0] p_read3;
input  [15:0] p_read14;
input  [5:0] p_read25;
input   ap_clk;
input   ap_rst;
input   HwReg_frm_buffer_ap_vld;
input   HwReg_frm_buffer2_ap_vld;
input   p_read_ap_vld;
input   p_read14_ap_vld;
input   p_read25_ap_vld;
input   ap_start;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input   p_read3_ap_vld;
input   p_read2_ap_vld;
input   p_read1_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [31:0] entry_proc_U0_ap_return_0;
wire   [31:0] entry_proc_U0_ap_return_1;
wire   [13:0] entry_proc_U0_ap_return_2;
wire   [15:0] entry_proc_U0_ap_return_3;
wire   [5:0] entry_proc_U0_ap_return_4;
wire    ap_channel_done_video_format_c11_channel;
wire    video_format_c11_channel_full_n;
reg    ap_sync_reg_channel_write_video_format_c11_channel;
wire    ap_sync_channel_write_video_format_c11_channel;
wire    ap_channel_done_stride_c_channel;
wire    stride_c_channel_full_n;
reg    ap_sync_reg_channel_write_stride_c_channel;
wire    ap_sync_channel_write_stride_c_channel;
wire    ap_channel_done_WidthInBytes_c9_channel;
wire    WidthInBytes_c9_channel_full_n;
reg    ap_sync_reg_channel_write_WidthInBytes_c9_channel;
wire    ap_sync_channel_write_WidthInBytes_c9_channel;
wire    ap_channel_done_HwReg_frm_buffer2_c_channel;
wire    HwReg_frm_buffer2_c_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel;
wire    ap_sync_channel_write_HwReg_frm_buffer2_c_channel;
wire    ap_channel_done_HwReg_frm_buffer_c_channel;
wire    HwReg_frm_buffer_c_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel;
wire    ap_sync_channel_write_HwReg_frm_buffer_c_channel;
wire    AXIvideo2MultiPixStream_U0_ap_start;
wire    AXIvideo2MultiPixStream_U0_ap_done;
wire    AXIvideo2MultiPixStream_U0_ap_continue;
wire    AXIvideo2MultiPixStream_U0_ap_idle;
wire    AXIvideo2MultiPixStream_U0_ap_ready;
wire    AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
wire   [23:0] AXIvideo2MultiPixStream_U0_img_din;
wire    AXIvideo2MultiPixStream_U0_img_write;
wire   [9:0] AXIvideo2MultiPixStream_U0_height_c10_din;
wire    AXIvideo2MultiPixStream_U0_height_c10_write;
wire    MultiPixStream2Bytes_U0_ap_start;
wire    MultiPixStream2Bytes_U0_ap_done;
wire    MultiPixStream2Bytes_U0_ap_continue;
wire    MultiPixStream2Bytes_U0_ap_idle;
wire    MultiPixStream2Bytes_U0_ap_ready;
wire    MultiPixStream2Bytes_U0_img_read;
wire   [63:0] MultiPixStream2Bytes_U0_bytePlanes_01_din;
wire    MultiPixStream2Bytes_U0_bytePlanes_01_write;
wire   [63:0] MultiPixStream2Bytes_U0_bytePlanes_12_din;
wire    MultiPixStream2Bytes_U0_bytePlanes_12_write;
wire    MultiPixStream2Bytes_U0_Height_read;
wire   [13:0] MultiPixStream2Bytes_U0_WidthInBytes_c_din;
wire    MultiPixStream2Bytes_U0_WidthInBytes_c_write;
wire   [9:0] MultiPixStream2Bytes_U0_height_c_din;
wire    MultiPixStream2Bytes_U0_height_c_write;
wire   [5:0] MultiPixStream2Bytes_U0_video_format_c_din;
wire    MultiPixStream2Bytes_U0_video_format_c_write;
wire    Bytes2AXIMMvideo_U0_ap_start;
wire    Bytes2AXIMMvideo_U0_ap_done;
wire    Bytes2AXIMMvideo_U0_ap_continue;
wire    Bytes2AXIMMvideo_U0_ap_idle;
wire    Bytes2AXIMMvideo_U0_ap_ready;
wire    Bytes2AXIMMvideo_U0_bytePlanes_01_read;
wire    Bytes2AXIMMvideo_U0_bytePlanes_12_read;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID;
wire   [63:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA;
wire   [7:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WID;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_ARVALID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARADDR;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARID;
wire   [31:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLEN;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARSIZE;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARBURST;
wire   [1:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLOCK;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARCACHE;
wire   [2:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARPROT;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARQOS;
wire   [3:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARREGION;
wire   [0:0] Bytes2AXIMMvideo_U0_m_axi_mm_video_ARUSER;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_RREADY;
wire    Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY;
wire    Bytes2AXIMMvideo_U0_Height_read;
wire    Bytes2AXIMMvideo_U0_WidthInBytes_read;
wire    Bytes2AXIMMvideo_U0_VideoFormat_read;
wire   [31:0] HwReg_frm_buffer_c_channel_dout;
wire    HwReg_frm_buffer_c_channel_empty_n;
wire   [31:0] HwReg_frm_buffer2_c_channel_dout;
wire    HwReg_frm_buffer2_c_channel_empty_n;
wire   [13:0] WidthInBytes_c9_channel_dout;
wire    WidthInBytes_c9_channel_empty_n;
wire   [15:0] stride_c_channel_dout;
wire    stride_c_channel_empty_n;
wire   [5:0] video_format_c11_channel_dout;
wire    video_format_c11_channel_empty_n;
wire    img_full_n;
wire   [23:0] img_dout;
wire    img_empty_n;
wire    height_c10_full_n;
wire   [9:0] height_c10_dout;
wire    height_c10_empty_n;
wire    bytePlanes_plane0_full_n;
wire   [63:0] bytePlanes_plane0_dout;
wire    bytePlanes_plane0_empty_n;
wire    bytePlanes_plane1_full_n;
wire   [63:0] bytePlanes_plane1_dout;
wire    bytePlanes_plane1_empty_n;
wire    WidthInBytes_c_full_n;
wire   [13:0] WidthInBytes_c_dout;
wire    WidthInBytes_c_empty_n;
wire    height_c_full_n;
wire   [9:0] height_c_dout;
wire    height_c_empty_n;
wire    video_format_c_full_n;
wire   [5:0] video_format_c_dout;
wire    video_format_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_video_format_c11_channel = 1'b0;
#0 ap_sync_reg_channel_write_stride_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_WidthInBytes_c9_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready = 1'b0;
end

h264_v_frmbuf_wr_0_0_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .HwReg_frm_buffer(HwReg_frm_buffer),
    .HwReg_frm_buffer2(HwReg_frm_buffer2),
    .p_read2(p_read),
    .p_read8(p_read14),
    .p_read12(p_read25),
    .ap_return_0(entry_proc_U0_ap_return_0),
    .ap_return_1(entry_proc_U0_ap_return_1),
    .ap_return_2(entry_proc_U0_ap_return_2),
    .ap_return_3(entry_proc_U0_ap_return_3),
    .ap_return_4(entry_proc_U0_ap_return_4)
);

h264_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream AXIvideo2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2MultiPixStream_U0_ap_start),
    .ap_done(AXIvideo2MultiPixStream_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_U0_ap_ready),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TREADY(AXIvideo2MultiPixStream_U0_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .img_din(AXIvideo2MultiPixStream_U0_img_din),
    .img_full_n(img_full_n),
    .img_write(AXIvideo2MultiPixStream_U0_img_write),
    .p_read(p_read3),
    .p_read1(p_read2),
    .p_read2(p_read1),
    .height_c10_din(AXIvideo2MultiPixStream_U0_height_c10_din),
    .height_c10_full_n(height_c10_full_n),
    .height_c10_write(AXIvideo2MultiPixStream_U0_height_c10_write)
);

h264_v_frmbuf_wr_0_0_MultiPixStream2Bytes MultiPixStream2Bytes_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MultiPixStream2Bytes_U0_ap_start),
    .ap_done(MultiPixStream2Bytes_U0_ap_done),
    .ap_continue(MultiPixStream2Bytes_U0_ap_continue),
    .ap_idle(MultiPixStream2Bytes_U0_ap_idle),
    .ap_ready(MultiPixStream2Bytes_U0_ap_ready),
    .img_dout(img_dout),
    .img_empty_n(img_empty_n),
    .img_read(MultiPixStream2Bytes_U0_img_read),
    .bytePlanes_01_din(MultiPixStream2Bytes_U0_bytePlanes_01_din),
    .bytePlanes_01_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_01_write(MultiPixStream2Bytes_U0_bytePlanes_01_write),
    .bytePlanes_12_din(MultiPixStream2Bytes_U0_bytePlanes_12_din),
    .bytePlanes_12_full_n(bytePlanes_plane1_full_n),
    .bytePlanes_12_write(MultiPixStream2Bytes_U0_bytePlanes_12_write),
    .Height_dout(height_c10_dout),
    .Height_empty_n(height_c10_empty_n),
    .Height_read(MultiPixStream2Bytes_U0_Height_read),
    .p_read(WidthInBytes_c9_channel_dout),
    .p_read1(video_format_c11_channel_dout),
    .WidthInBytes_c_din(MultiPixStream2Bytes_U0_WidthInBytes_c_din),
    .WidthInBytes_c_full_n(WidthInBytes_c_full_n),
    .WidthInBytes_c_write(MultiPixStream2Bytes_U0_WidthInBytes_c_write),
    .height_c_din(MultiPixStream2Bytes_U0_height_c_din),
    .height_c_full_n(height_c_full_n),
    .height_c_write(MultiPixStream2Bytes_U0_height_c_write),
    .video_format_c_din(MultiPixStream2Bytes_U0_video_format_c_din),
    .video_format_c_full_n(video_format_c_full_n),
    .video_format_c_write(MultiPixStream2Bytes_U0_video_format_c_write)
);

h264_v_frmbuf_wr_0_0_Bytes2AXIMMvideo Bytes2AXIMMvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Bytes2AXIMMvideo_U0_ap_start),
    .ap_done(Bytes2AXIMMvideo_U0_ap_done),
    .ap_continue(Bytes2AXIMMvideo_U0_ap_continue),
    .ap_idle(Bytes2AXIMMvideo_U0_ap_idle),
    .ap_ready(Bytes2AXIMMvideo_U0_ap_ready),
    .bytePlanes_01_dout(bytePlanes_plane0_dout),
    .bytePlanes_01_empty_n(bytePlanes_plane0_empty_n),
    .bytePlanes_01_read(Bytes2AXIMMvideo_U0_bytePlanes_01_read),
    .bytePlanes_12_dout(bytePlanes_plane1_dout),
    .bytePlanes_12_empty_n(bytePlanes_plane1_empty_n),
    .bytePlanes_12_read(Bytes2AXIMMvideo_U0_bytePlanes_12_read),
    .m_axi_mm_video_AWVALID(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID),
    .m_axi_mm_video_AWREADY(m_axi_mm_video_AWREADY),
    .m_axi_mm_video_AWADDR(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR),
    .m_axi_mm_video_AWID(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID),
    .m_axi_mm_video_AWLEN(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN),
    .m_axi_mm_video_AWSIZE(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE),
    .m_axi_mm_video_AWBURST(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST),
    .m_axi_mm_video_AWLOCK(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK),
    .m_axi_mm_video_AWCACHE(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE),
    .m_axi_mm_video_AWPROT(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT),
    .m_axi_mm_video_AWQOS(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS),
    .m_axi_mm_video_AWREGION(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION),
    .m_axi_mm_video_AWUSER(Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER),
    .m_axi_mm_video_WVALID(Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID),
    .m_axi_mm_video_WREADY(m_axi_mm_video_WREADY),
    .m_axi_mm_video_WDATA(Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA),
    .m_axi_mm_video_WSTRB(Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB),
    .m_axi_mm_video_WLAST(Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST),
    .m_axi_mm_video_WID(Bytes2AXIMMvideo_U0_m_axi_mm_video_WID),
    .m_axi_mm_video_WUSER(Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER),
    .m_axi_mm_video_ARVALID(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARVALID),
    .m_axi_mm_video_ARREADY(1'b0),
    .m_axi_mm_video_ARADDR(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARADDR),
    .m_axi_mm_video_ARID(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARID),
    .m_axi_mm_video_ARLEN(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLEN),
    .m_axi_mm_video_ARSIZE(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARSIZE),
    .m_axi_mm_video_ARBURST(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARBURST),
    .m_axi_mm_video_ARLOCK(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARLOCK),
    .m_axi_mm_video_ARCACHE(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARCACHE),
    .m_axi_mm_video_ARPROT(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARPROT),
    .m_axi_mm_video_ARQOS(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARQOS),
    .m_axi_mm_video_ARREGION(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARREGION),
    .m_axi_mm_video_ARUSER(Bytes2AXIMMvideo_U0_m_axi_mm_video_ARUSER),
    .m_axi_mm_video_RVALID(1'b0),
    .m_axi_mm_video_RREADY(Bytes2AXIMMvideo_U0_m_axi_mm_video_RREADY),
    .m_axi_mm_video_RDATA(64'd0),
    .m_axi_mm_video_RLAST(1'b0),
    .m_axi_mm_video_RID(1'd0),
    .m_axi_mm_video_RUSER(1'd0),
    .m_axi_mm_video_RRESP(2'd0),
    .m_axi_mm_video_BVALID(m_axi_mm_video_BVALID),
    .m_axi_mm_video_BREADY(Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY),
    .m_axi_mm_video_BRESP(m_axi_mm_video_BRESP),
    .m_axi_mm_video_BID(m_axi_mm_video_BID),
    .m_axi_mm_video_BUSER(m_axi_mm_video_BUSER),
    .p_read(HwReg_frm_buffer_c_channel_dout),
    .p_read1(HwReg_frm_buffer2_c_channel_dout),
    .Height_dout(height_c_dout),
    .Height_empty_n(height_c_empty_n),
    .Height_read(Bytes2AXIMMvideo_U0_Height_read),
    .WidthInBytes_dout(WidthInBytes_c_dout),
    .WidthInBytes_empty_n(WidthInBytes_c_empty_n),
    .WidthInBytes_read(Bytes2AXIMMvideo_U0_WidthInBytes_read),
    .p_read2(stride_c_channel_dout),
    .VideoFormat_dout(video_format_c_dout),
    .VideoFormat_empty_n(video_format_c_empty_n),
    .VideoFormat_read(Bytes2AXIMMvideo_U0_VideoFormat_read)
);

h264_v_frmbuf_wr_0_0_fifo_w32_d3_S HwReg_frm_buffer_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ap_return_0),
    .if_full_n(HwReg_frm_buffer_c_channel_full_n),
    .if_write(ap_channel_done_HwReg_frm_buffer_c_channel),
    .if_dout(HwReg_frm_buffer_c_channel_dout),
    .if_empty_n(HwReg_frm_buffer_c_channel_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_ap_ready)
);

h264_v_frmbuf_wr_0_0_fifo_w32_d3_S HwReg_frm_buffer2_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ap_return_1),
    .if_full_n(HwReg_frm_buffer2_c_channel_full_n),
    .if_write(ap_channel_done_HwReg_frm_buffer2_c_channel),
    .if_dout(HwReg_frm_buffer2_c_channel_dout),
    .if_empty_n(HwReg_frm_buffer2_c_channel_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_ap_ready)
);

h264_v_frmbuf_wr_0_0_fifo_w14_d2_S WidthInBytes_c9_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ap_return_2),
    .if_full_n(WidthInBytes_c9_channel_full_n),
    .if_write(ap_channel_done_WidthInBytes_c9_channel),
    .if_dout(WidthInBytes_c9_channel_dout),
    .if_empty_n(WidthInBytes_c9_channel_empty_n),
    .if_read(MultiPixStream2Bytes_U0_ap_ready)
);

h264_v_frmbuf_wr_0_0_fifo_w16_d3_S stride_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ap_return_3),
    .if_full_n(stride_c_channel_full_n),
    .if_write(ap_channel_done_stride_c_channel),
    .if_dout(stride_c_channel_dout),
    .if_empty_n(stride_c_channel_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_ap_ready)
);

h264_v_frmbuf_wr_0_0_fifo_w6_d2_S video_format_c11_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ap_return_4),
    .if_full_n(video_format_c11_channel_full_n),
    .if_write(ap_channel_done_video_format_c11_channel),
    .if_dout(video_format_c11_channel_dout),
    .if_empty_n(video_format_c11_channel_empty_n),
    .if_read(MultiPixStream2Bytes_U0_ap_ready)
);

h264_v_frmbuf_wr_0_0_fifo_w24_d2_S img_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_img_din),
    .if_full_n(img_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_img_write),
    .if_dout(img_dout),
    .if_empty_n(img_empty_n),
    .if_read(MultiPixStream2Bytes_U0_img_read)
);

h264_v_frmbuf_wr_0_0_fifo_w10_d2_S height_c10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_height_c10_din),
    .if_full_n(height_c10_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_height_c10_write),
    .if_dout(height_c10_dout),
    .if_empty_n(height_c10_empty_n),
    .if_read(MultiPixStream2Bytes_U0_Height_read)
);

h264_v_frmbuf_wr_0_0_fifo_w64_d320_B bytePlanes_plane0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_bytePlanes_01_din),
    .if_full_n(bytePlanes_plane0_full_n),
    .if_write(MultiPixStream2Bytes_U0_bytePlanes_01_write),
    .if_dout(bytePlanes_plane0_dout),
    .if_empty_n(bytePlanes_plane0_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_bytePlanes_01_read)
);

h264_v_frmbuf_wr_0_0_fifo_w64_d320_B bytePlanes_plane1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_bytePlanes_12_din),
    .if_full_n(bytePlanes_plane1_full_n),
    .if_write(MultiPixStream2Bytes_U0_bytePlanes_12_write),
    .if_dout(bytePlanes_plane1_dout),
    .if_empty_n(bytePlanes_plane1_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_bytePlanes_12_read)
);

h264_v_frmbuf_wr_0_0_fifo_w14_d2_S WidthInBytes_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_WidthInBytes_c_din),
    .if_full_n(WidthInBytes_c_full_n),
    .if_write(MultiPixStream2Bytes_U0_WidthInBytes_c_write),
    .if_dout(WidthInBytes_c_dout),
    .if_empty_n(WidthInBytes_c_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_WidthInBytes_read)
);

h264_v_frmbuf_wr_0_0_fifo_w10_d2_S height_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_height_c_din),
    .if_full_n(height_c_full_n),
    .if_write(MultiPixStream2Bytes_U0_height_c_write),
    .if_dout(height_c_dout),
    .if_empty_n(height_c_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_Height_read)
);

h264_v_frmbuf_wr_0_0_fifo_w6_d2_S video_format_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MultiPixStream2Bytes_U0_video_format_c_din),
    .if_full_n(video_format_c_full_n),
    .if_write(MultiPixStream2Bytes_U0_video_format_c_write),
    .if_dout(video_format_c_dout),
    .if_empty_n(video_format_c_empty_n),
    .if_read(Bytes2AXIMMvideo_U0_VideoFormat_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel <= 1'b0;
    end else begin
        if (((entry_proc_U0_ap_done & entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel <= ap_sync_channel_write_HwReg_frm_buffer2_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel <= 1'b0;
    end else begin
        if (((entry_proc_U0_ap_done & entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel <= ap_sync_channel_write_HwReg_frm_buffer_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_WidthInBytes_c9_channel <= 1'b0;
    end else begin
        if (((entry_proc_U0_ap_done & entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_WidthInBytes_c9_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_WidthInBytes_c9_channel <= ap_sync_channel_write_WidthInBytes_c9_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_stride_c_channel <= 1'b0;
    end else begin
        if (((entry_proc_U0_ap_done & entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_stride_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_stride_c_channel <= ap_sync_channel_write_stride_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_video_format_c11_channel <= 1'b0;
    end else begin
        if (((entry_proc_U0_ap_done & entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_video_format_c11_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_video_format_c11_channel <= ap_sync_channel_write_video_format_c11_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign AXIvideo2MultiPixStream_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready ^ 1'b1) & ap_start);

assign Bytes2AXIMMvideo_U0_ap_continue = ap_continue;

assign Bytes2AXIMMvideo_U0_ap_start = (stride_c_channel_empty_n & HwReg_frm_buffer_c_channel_empty_n & HwReg_frm_buffer2_c_channel_empty_n);

assign MultiPixStream2Bytes_U0_ap_continue = 1'b1;

assign MultiPixStream2Bytes_U0_ap_start = (video_format_c11_channel_empty_n & WidthInBytes_c9_channel_empty_n);

assign ap_channel_done_HwReg_frm_buffer2_c_channel = ((ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel ^ 1'b1) & entry_proc_U0_ap_done);

assign ap_channel_done_HwReg_frm_buffer_c_channel = ((ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel ^ 1'b1) & entry_proc_U0_ap_done);

assign ap_channel_done_WidthInBytes_c9_channel = ((ap_sync_reg_channel_write_WidthInBytes_c9_channel ^ 1'b1) & entry_proc_U0_ap_done);

assign ap_channel_done_stride_c_channel = ((ap_sync_reg_channel_write_stride_c_channel ^ 1'b1) & entry_proc_U0_ap_done);

assign ap_channel_done_video_format_c11_channel = ((ap_sync_reg_channel_write_video_format_c11_channel ^ 1'b1) & entry_proc_U0_ap_done);

assign ap_done = Bytes2AXIMMvideo_U0_ap_done;

assign ap_idle = ((1'b1 ^ WidthInBytes_c9_channel_empty_n) & (1'b1 ^ HwReg_frm_buffer2_c_channel_empty_n) & (1'b1 ^ HwReg_frm_buffer_c_channel_empty_n) & (video_format_c11_channel_empty_n ^ 1'b1) & (stride_c_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle & MultiPixStream2Bytes_U0_ap_idle & Bytes2AXIMMvideo_U0_ap_idle & AXIvideo2MultiPixStream_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_AXIvideo2MultiPixStream_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready | AXIvideo2MultiPixStream_U0_ap_ready);

assign ap_sync_channel_write_HwReg_frm_buffer2_c_channel = ((ap_channel_done_HwReg_frm_buffer2_c_channel & HwReg_frm_buffer2_c_channel_full_n) | ap_sync_reg_channel_write_HwReg_frm_buffer2_c_channel);

assign ap_sync_channel_write_HwReg_frm_buffer_c_channel = ((ap_channel_done_HwReg_frm_buffer_c_channel & HwReg_frm_buffer_c_channel_full_n) | ap_sync_reg_channel_write_HwReg_frm_buffer_c_channel);

assign ap_sync_channel_write_WidthInBytes_c9_channel = ((ap_channel_done_WidthInBytes_c9_channel & WidthInBytes_c9_channel_full_n) | ap_sync_reg_channel_write_WidthInBytes_c9_channel);

assign ap_sync_channel_write_stride_c_channel = ((stride_c_channel_full_n & ap_channel_done_stride_c_channel) | ap_sync_reg_channel_write_stride_c_channel);

assign ap_sync_channel_write_video_format_c11_channel = ((video_format_c11_channel_full_n & ap_channel_done_video_format_c11_channel) | ap_sync_reg_channel_write_video_format_c11_channel);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);

assign entry_proc_U0_ap_continue = (ap_sync_channel_write_video_format_c11_channel & ap_sync_channel_write_stride_c_channel & ap_sync_channel_write_WidthInBytes_c9_channel & ap_sync_channel_write_HwReg_frm_buffer_c_channel & ap_sync_channel_write_HwReg_frm_buffer2_c_channel);

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign m_axi_mm_video_ARADDR = 32'd0;

assign m_axi_mm_video_ARBURST = 2'd0;

assign m_axi_mm_video_ARCACHE = 4'd0;

assign m_axi_mm_video_ARID = 1'd0;

assign m_axi_mm_video_ARLEN = 32'd0;

assign m_axi_mm_video_ARLOCK = 2'd0;

assign m_axi_mm_video_ARPROT = 3'd0;

assign m_axi_mm_video_ARQOS = 4'd0;

assign m_axi_mm_video_ARREGION = 4'd0;

assign m_axi_mm_video_ARSIZE = 3'd0;

assign m_axi_mm_video_ARUSER = 1'd0;

assign m_axi_mm_video_ARVALID = 1'b0;

assign m_axi_mm_video_AWADDR = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWADDR;

assign m_axi_mm_video_AWBURST = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWBURST;

assign m_axi_mm_video_AWCACHE = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWCACHE;

assign m_axi_mm_video_AWID = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWID;

assign m_axi_mm_video_AWLEN = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLEN;

assign m_axi_mm_video_AWLOCK = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWLOCK;

assign m_axi_mm_video_AWPROT = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWPROT;

assign m_axi_mm_video_AWQOS = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWQOS;

assign m_axi_mm_video_AWREGION = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWREGION;

assign m_axi_mm_video_AWSIZE = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWSIZE;

assign m_axi_mm_video_AWUSER = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWUSER;

assign m_axi_mm_video_AWVALID = Bytes2AXIMMvideo_U0_m_axi_mm_video_AWVALID;

assign m_axi_mm_video_BREADY = Bytes2AXIMMvideo_U0_m_axi_mm_video_BREADY;

assign m_axi_mm_video_RREADY = 1'b0;

assign m_axi_mm_video_WDATA = Bytes2AXIMMvideo_U0_m_axi_mm_video_WDATA;

assign m_axi_mm_video_WID = Bytes2AXIMMvideo_U0_m_axi_mm_video_WID;

assign m_axi_mm_video_WLAST = Bytes2AXIMMvideo_U0_m_axi_mm_video_WLAST;

assign m_axi_mm_video_WSTRB = Bytes2AXIMMvideo_U0_m_axi_mm_video_WSTRB;

assign m_axi_mm_video_WUSER = Bytes2AXIMMvideo_U0_m_axi_mm_video_WUSER;

assign m_axi_mm_video_WVALID = Bytes2AXIMMvideo_U0_m_axi_mm_video_WVALID;

assign s_axis_video_TREADY = AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;

endmodule //h264_v_frmbuf_wr_0_0_FrmbufWrHlsDataFlow
