// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="h264_v_frmbuf_wr_0_0_v_frmbuf_wr,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=3478,HLS_SYN_LUT=4899,HLS_VERSION=2021_1}" *)

module h264_v_frmbuf_wr_0_0_v_frmbuf_wr (
// synthesis translate_off
    kernel_block,
// synthesis translate_on
        ap_clk,
        ap_rst_n,
        m_axi_mm_video_AWVALID,
        m_axi_mm_video_AWREADY,
        m_axi_mm_video_AWADDR,
        m_axi_mm_video_AWID,
        m_axi_mm_video_AWLEN,
        m_axi_mm_video_AWSIZE,
        m_axi_mm_video_AWBURST,
        m_axi_mm_video_AWLOCK,
        m_axi_mm_video_AWCACHE,
        m_axi_mm_video_AWPROT,
        m_axi_mm_video_AWQOS,
        m_axi_mm_video_AWREGION,
        m_axi_mm_video_AWUSER,
        m_axi_mm_video_WVALID,
        m_axi_mm_video_WREADY,
        m_axi_mm_video_WDATA,
        m_axi_mm_video_WSTRB,
        m_axi_mm_video_WLAST,
        m_axi_mm_video_WID,
        m_axi_mm_video_WUSER,
        m_axi_mm_video_ARVALID,
        m_axi_mm_video_ARREADY,
        m_axi_mm_video_ARADDR,
        m_axi_mm_video_ARID,
        m_axi_mm_video_ARLEN,
        m_axi_mm_video_ARSIZE,
        m_axi_mm_video_ARBURST,
        m_axi_mm_video_ARLOCK,
        m_axi_mm_video_ARCACHE,
        m_axi_mm_video_ARPROT,
        m_axi_mm_video_ARQOS,
        m_axi_mm_video_ARREGION,
        m_axi_mm_video_ARUSER,
        m_axi_mm_video_RVALID,
        m_axi_mm_video_RREADY,
        m_axi_mm_video_RDATA,
        m_axi_mm_video_RLAST,
        m_axi_mm_video_RID,
        m_axi_mm_video_RUSER,
        m_axi_mm_video_RRESP,
        m_axi_mm_video_BVALID,
        m_axi_mm_video_BREADY,
        m_axi_mm_video_BRESP,
        m_axi_mm_video_BID,
        m_axi_mm_video_BUSER,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MM_VIDEO_ID_WIDTH = 1;
parameter    C_M_AXI_MM_VIDEO_ADDR_WIDTH = 32;
parameter    C_M_AXI_MM_VIDEO_DATA_WIDTH = 64;
parameter    C_M_AXI_MM_VIDEO_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MM_VIDEO_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MM_VIDEO_WUSER_WIDTH = 1;
parameter    C_M_AXI_MM_VIDEO_RUSER_WIDTH = 1;
parameter    C_M_AXI_MM_VIDEO_BUSER_WIDTH = 1;
parameter    C_M_AXI_MM_VIDEO_USER_VALUE = 0;
parameter    C_M_AXI_MM_VIDEO_PROT_VALUE = 0;
parameter    C_M_AXI_MM_VIDEO_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MM_VIDEO_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

// synthesis translate_off
output kernel_block;
// synthesis translate_on
input   ap_clk;
input   ap_rst_n;
output   m_axi_mm_video_AWVALID;
input   m_axi_mm_video_AWREADY;
output  [C_M_AXI_MM_VIDEO_ADDR_WIDTH - 1:0] m_axi_mm_video_AWADDR;
output  [C_M_AXI_MM_VIDEO_ID_WIDTH - 1:0] m_axi_mm_video_AWID;
output  [7:0] m_axi_mm_video_AWLEN;
output  [2:0] m_axi_mm_video_AWSIZE;
output  [1:0] m_axi_mm_video_AWBURST;
output  [1:0] m_axi_mm_video_AWLOCK;
output  [3:0] m_axi_mm_video_AWCACHE;
output  [2:0] m_axi_mm_video_AWPROT;
output  [3:0] m_axi_mm_video_AWQOS;
output  [3:0] m_axi_mm_video_AWREGION;
output  [C_M_AXI_MM_VIDEO_AWUSER_WIDTH - 1:0] m_axi_mm_video_AWUSER;
output   m_axi_mm_video_WVALID;
input   m_axi_mm_video_WREADY;
output  [C_M_AXI_MM_VIDEO_DATA_WIDTH - 1:0] m_axi_mm_video_WDATA;
output  [C_M_AXI_MM_VIDEO_WSTRB_WIDTH - 1:0] m_axi_mm_video_WSTRB;
output   m_axi_mm_video_WLAST;
output  [C_M_AXI_MM_VIDEO_ID_WIDTH - 1:0] m_axi_mm_video_WID;
output  [C_M_AXI_MM_VIDEO_WUSER_WIDTH - 1:0] m_axi_mm_video_WUSER;
output   m_axi_mm_video_ARVALID;
input   m_axi_mm_video_ARREADY;
output  [C_M_AXI_MM_VIDEO_ADDR_WIDTH - 1:0] m_axi_mm_video_ARADDR;
output  [C_M_AXI_MM_VIDEO_ID_WIDTH - 1:0] m_axi_mm_video_ARID;
output  [7:0] m_axi_mm_video_ARLEN;
output  [2:0] m_axi_mm_video_ARSIZE;
output  [1:0] m_axi_mm_video_ARBURST;
output  [1:0] m_axi_mm_video_ARLOCK;
output  [3:0] m_axi_mm_video_ARCACHE;
output  [2:0] m_axi_mm_video_ARPROT;
output  [3:0] m_axi_mm_video_ARQOS;
output  [3:0] m_axi_mm_video_ARREGION;
output  [C_M_AXI_MM_VIDEO_ARUSER_WIDTH - 1:0] m_axi_mm_video_ARUSER;
input   m_axi_mm_video_RVALID;
output   m_axi_mm_video_RREADY;
input  [C_M_AXI_MM_VIDEO_DATA_WIDTH - 1:0] m_axi_mm_video_RDATA;
input   m_axi_mm_video_RLAST;
input  [C_M_AXI_MM_VIDEO_ID_WIDTH - 1:0] m_axi_mm_video_RID;
input  [C_M_AXI_MM_VIDEO_RUSER_WIDTH - 1:0] m_axi_mm_video_RUSER;
input  [1:0] m_axi_mm_video_RRESP;
input   m_axi_mm_video_BVALID;
output   m_axi_mm_video_BREADY;
input  [1:0] m_axi_mm_video_BRESP;
input  [C_M_AXI_MM_VIDEO_ID_WIDTH - 1:0] m_axi_mm_video_BID;
input  [C_M_AXI_MM_VIDEO_BUSER_WIDTH - 1:0] m_axi_mm_video_BUSER;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] width;
wire   [15:0] height;
wire   [15:0] stride;
wire   [15:0] video_format;
wire   [31:0] frm_buffer;
wire   [31:0] frm_buffer2;
wire   [5:0] BYTES_PER_PIXEL_address0;
reg    BYTES_PER_PIXEL_ce0;
wire   [2:0] BYTES_PER_PIXEL_q0;
wire   [5:0] MEMORY2LIVE_address0;
reg    MEMORY2LIVE_ce0;
wire   [2:0] MEMORY2LIVE_q0;
wire   [5:0] empty_48_fu_185_p1;
reg   [5:0] empty_48_reg_218;
wire   [10:0] empty_fu_195_p1;
reg   [10:0] empty_reg_233;
wire    ap_CS_fsm_state2;
wire   [13:0] WidthInBytes_fu_207_p2;
reg   [13:0] WidthInBytes_reg_238;
reg   [2:0] colorFormat_reg_243;
reg   [31:0] frm_buffer2_read_reg_248;
wire    ap_CS_fsm_state3;
reg   [31:0] frm_buffer_read_reg_253;
wire   [9:0] empty_49_fu_213_p1;
reg   [9:0] empty_49_reg_263;
wire    grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWVALID;
wire   [31:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWADDR;
wire   [0:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWID;
wire   [31:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWLEN;
wire   [2:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWSIZE;
wire   [1:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWBURST;
wire   [1:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWLOCK;
wire   [3:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWCACHE;
wire   [2:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWPROT;
wire   [3:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWQOS;
wire   [3:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWREGION;
wire   [0:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWUSER;
wire    grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WVALID;
wire   [63:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WDATA;
wire   [7:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WSTRB;
wire    grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WLAST;
wire   [0:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WID;
wire   [0:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WUSER;
wire    grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARVALID;
wire   [31:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARADDR;
wire   [0:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARID;
wire   [31:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARLEN;
wire   [2:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARSIZE;
wire   [1:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARBURST;
wire   [1:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARLOCK;
wire   [3:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARCACHE;
wire   [2:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARPROT;
wire   [3:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARQOS;
wire   [3:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARREGION;
wire   [0:0] grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARUSER;
wire    grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_RREADY;
wire    grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_BREADY;
wire    grp_FrmbufWrHlsDataFlow_fu_154_ap_start;
wire    grp_FrmbufWrHlsDataFlow_fu_154_s_axis_video_TREADY;
wire    grp_FrmbufWrHlsDataFlow_fu_154_ap_done;
wire    grp_FrmbufWrHlsDataFlow_fu_154_ap_ready;
wire    grp_FrmbufWrHlsDataFlow_fu_154_ap_idle;
reg    grp_FrmbufWrHlsDataFlow_fu_154_ap_continue;
wire    flush;
reg    s_axi_CTRL_flush_done;
wire    m_axi_mm_video_flush_done;
reg    mm_video_AWVALID;
wire    mm_video_AWREADY;
reg    mm_video_WVALID;
wire    mm_video_WREADY;
wire    mm_video_ARREADY;
wire    mm_video_RVALID;
wire   [63:0] mm_video_RDATA;
wire    mm_video_RLAST;
wire   [0:0] mm_video_RID;
wire   [0:0] mm_video_RUSER;
wire   [1:0] mm_video_RRESP;
wire    mm_video_BVALID;
reg    mm_video_BREADY;
wire   [1:0] mm_video_BRESP;
wire   [0:0] mm_video_BID;
wire   [0:0] mm_video_BUSER;
reg    grp_FrmbufWrHlsDataFlow_fu_154_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready;
wire    ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_done;
reg    ap_block_state4_on_subcall_done;
reg    ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready;
reg    ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_done;
wire   [31:0] zext_ln151_fu_189_p1;
wire   [10:0] WidthInBytes_fu_207_p0;
wire   [2:0] WidthInBytes_fu_207_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [23:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [2:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [2:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire   [13:0] WidthInBytes_fu_207_p00;
wire   [13:0] WidthInBytes_fu_207_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_FrmbufWrHlsDataFlow_fu_154_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready = 1'b0;
#0 ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_done = 1'b0;
end

h264_v_frmbuf_wr_0_0_BYTES_PER_PIXEL #(
    .DataWidth( 3 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
BYTES_PER_PIXEL_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(BYTES_PER_PIXEL_address0),
    .ce0(BYTES_PER_PIXEL_ce0),
    .q0(BYTES_PER_PIXEL_q0)
);

h264_v_frmbuf_wr_0_0_MEMORY2LIVE #(
    .DataWidth( 3 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
MEMORY2LIVE_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MEMORY2LIVE_address0),
    .ce0(MEMORY2LIVE_ce0),
    .q0(MEMORY2LIVE_q0)
);

h264_v_frmbuf_wr_0_0_FrmbufWrHlsDataFlow grp_FrmbufWrHlsDataFlow_fu_154(
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .m_axi_mm_video_AWVALID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWVALID),
    .m_axi_mm_video_AWREADY(mm_video_AWREADY),
    .m_axi_mm_video_AWADDR(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWADDR),
    .m_axi_mm_video_AWID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWID),
    .m_axi_mm_video_AWLEN(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWLEN),
    .m_axi_mm_video_AWSIZE(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWSIZE),
    .m_axi_mm_video_AWBURST(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWBURST),
    .m_axi_mm_video_AWLOCK(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWLOCK),
    .m_axi_mm_video_AWCACHE(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWCACHE),
    .m_axi_mm_video_AWPROT(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWPROT),
    .m_axi_mm_video_AWQOS(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWQOS),
    .m_axi_mm_video_AWREGION(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWREGION),
    .m_axi_mm_video_AWUSER(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWUSER),
    .m_axi_mm_video_WVALID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WVALID),
    .m_axi_mm_video_WREADY(mm_video_WREADY),
    .m_axi_mm_video_WDATA(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WDATA),
    .m_axi_mm_video_WSTRB(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WSTRB),
    .m_axi_mm_video_WLAST(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WLAST),
    .m_axi_mm_video_WID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WID),
    .m_axi_mm_video_WUSER(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WUSER),
    .m_axi_mm_video_ARVALID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARVALID),
    .m_axi_mm_video_ARREADY(1'b0),
    .m_axi_mm_video_ARADDR(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARADDR),
    .m_axi_mm_video_ARID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARID),
    .m_axi_mm_video_ARLEN(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARLEN),
    .m_axi_mm_video_ARSIZE(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARSIZE),
    .m_axi_mm_video_ARBURST(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARBURST),
    .m_axi_mm_video_ARLOCK(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARLOCK),
    .m_axi_mm_video_ARCACHE(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARCACHE),
    .m_axi_mm_video_ARPROT(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARPROT),
    .m_axi_mm_video_ARQOS(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARQOS),
    .m_axi_mm_video_ARREGION(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARREGION),
    .m_axi_mm_video_ARUSER(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_ARUSER),
    .m_axi_mm_video_RVALID(1'b0),
    .m_axi_mm_video_RREADY(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_RREADY),
    .m_axi_mm_video_RDATA(64'd0),
    .m_axi_mm_video_RLAST(1'b0),
    .m_axi_mm_video_RID(1'd0),
    .m_axi_mm_video_RUSER(1'd0),
    .m_axi_mm_video_RRESP(2'd0),
    .m_axi_mm_video_BVALID(mm_video_BVALID),
    .m_axi_mm_video_BREADY(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_BREADY),
    .m_axi_mm_video_BRESP(mm_video_BRESP),
    .m_axi_mm_video_BID(mm_video_BID),
    .m_axi_mm_video_BUSER(mm_video_BUSER),
    .HwReg_frm_buffer(frm_buffer_read_reg_253),
    .HwReg_frm_buffer2(frm_buffer2_read_reg_248),
    .p_read(WidthInBytes_reg_238),
    .p_read1(colorFormat_reg_243),
    .p_read2(empty_reg_233),
    .p_read3(empty_49_reg_263),
    .p_read14(stride),
    .p_read25(empty_48_reg_218),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .HwReg_frm_buffer_ap_vld(1'b1),
    .HwReg_frm_buffer2_ap_vld(1'b1),
    .p_read_ap_vld(1'b1),
    .p_read14_ap_vld(1'b1),
    .p_read25_ap_vld(1'b1),
    .ap_start(grp_FrmbufWrHlsDataFlow_fu_154_ap_start),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TREADY(grp_FrmbufWrHlsDataFlow_fu_154_s_axis_video_TREADY),
    .p_read3_ap_vld(1'b1),
    .p_read2_ap_vld(1'b1),
    .p_read1_ap_vld(1'b1),
    .ap_done(grp_FrmbufWrHlsDataFlow_fu_154_ap_done),
    .ap_ready(grp_FrmbufWrHlsDataFlow_fu_154_ap_ready),
    .ap_idle(grp_FrmbufWrHlsDataFlow_fu_154_ap_idle),
    .ap_continue(grp_FrmbufWrHlsDataFlow_fu_154_ap_continue)
);

h264_v_frmbuf_wr_0_0_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .width(width),
    .height(height),
    .stride(stride),
    .video_format(video_format),
    .frm_buffer(frm_buffer),
    .frm_buffer2(frm_buffer2),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .flush(flush),
    .flush_done(s_axi_CTRL_flush_done)
);

h264_v_frmbuf_wr_0_0_mm_video_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 105 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MM_VIDEO_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MM_VIDEO_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MM_VIDEO_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MM_VIDEO_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MM_VIDEO_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MM_VIDEO_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MM_VIDEO_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MM_VIDEO_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MM_VIDEO_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MM_VIDEO_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MM_VIDEO_CACHE_VALUE ))
mm_video_m_axi_U(
    .AWVALID(m_axi_mm_video_AWVALID),
    .AWREADY(m_axi_mm_video_AWREADY),
    .AWADDR(m_axi_mm_video_AWADDR),
    .AWID(m_axi_mm_video_AWID),
    .AWLEN(m_axi_mm_video_AWLEN),
    .AWSIZE(m_axi_mm_video_AWSIZE),
    .AWBURST(m_axi_mm_video_AWBURST),
    .AWLOCK(m_axi_mm_video_AWLOCK),
    .AWCACHE(m_axi_mm_video_AWCACHE),
    .AWPROT(m_axi_mm_video_AWPROT),
    .AWQOS(m_axi_mm_video_AWQOS),
    .AWREGION(m_axi_mm_video_AWREGION),
    .AWUSER(m_axi_mm_video_AWUSER),
    .WVALID(m_axi_mm_video_WVALID),
    .WREADY(m_axi_mm_video_WREADY),
    .WDATA(m_axi_mm_video_WDATA),
    .WSTRB(m_axi_mm_video_WSTRB),
    .WLAST(m_axi_mm_video_WLAST),
    .WID(m_axi_mm_video_WID),
    .WUSER(m_axi_mm_video_WUSER),
    .ARVALID(m_axi_mm_video_ARVALID),
    .ARREADY(m_axi_mm_video_ARREADY),
    .ARADDR(m_axi_mm_video_ARADDR),
    .ARID(m_axi_mm_video_ARID),
    .ARLEN(m_axi_mm_video_ARLEN),
    .ARSIZE(m_axi_mm_video_ARSIZE),
    .ARBURST(m_axi_mm_video_ARBURST),
    .ARLOCK(m_axi_mm_video_ARLOCK),
    .ARCACHE(m_axi_mm_video_ARCACHE),
    .ARPROT(m_axi_mm_video_ARPROT),
    .ARQOS(m_axi_mm_video_ARQOS),
    .ARREGION(m_axi_mm_video_ARREGION),
    .ARUSER(m_axi_mm_video_ARUSER),
    .RVALID(m_axi_mm_video_RVALID),
    .RREADY(m_axi_mm_video_RREADY),
    .RDATA(m_axi_mm_video_RDATA),
    .RLAST(m_axi_mm_video_RLAST),
    .RID(m_axi_mm_video_RID),
    .RUSER(m_axi_mm_video_RUSER),
    .RRESP(m_axi_mm_video_RRESP),
    .BVALID(m_axi_mm_video_BVALID),
    .BREADY(m_axi_mm_video_BREADY),
    .BRESP(m_axi_mm_video_BRESP),
    .BID(m_axi_mm_video_BID),
    .BUSER(m_axi_mm_video_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .flush(flush),
    .flush_done(m_axi_mm_video_flush_done),
    .I_ARVALID(1'b0),
    .I_ARREADY(mm_video_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(mm_video_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(mm_video_RDATA),
    .I_RID(mm_video_RID),
    .I_RUSER(mm_video_RUSER),
    .I_RRESP(mm_video_RRESP),
    .I_RLAST(mm_video_RLAST),
    .I_AWVALID(mm_video_AWVALID),
    .I_AWREADY(mm_video_AWREADY),
    .I_AWADDR(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWADDR),
    .I_AWID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWID),
    .I_AWLEN(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWLEN),
    .I_AWSIZE(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWSIZE),
    .I_AWLOCK(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWLOCK),
    .I_AWCACHE(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWCACHE),
    .I_AWQOS(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWQOS),
    .I_AWPROT(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWPROT),
    .I_AWUSER(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWUSER),
    .I_AWBURST(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWBURST),
    .I_AWREGION(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWREGION),
    .I_WVALID(mm_video_WVALID),
    .I_WREADY(mm_video_WREADY),
    .I_WDATA(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WDATA),
    .I_WID(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WID),
    .I_WUSER(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WUSER),
    .I_WLAST(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WLAST),
    .I_WSTRB(grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WSTRB),
    .I_BVALID(mm_video_BVALID),
    .I_BREADY(mm_video_BREADY),
    .I_BRESP(mm_video_BRESP),
    .I_BID(mm_video_BID),
    .I_BUSER(mm_video_BUSER)
);

h264_v_frmbuf_wr_0_0_mul_11ns_3ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 14 ))
mul_11ns_3ns_14_1_1_U129(
    .din0(WidthInBytes_fu_207_p0),
    .din1(WidthInBytes_fu_207_p1),
    .dout(WidthInBytes_fu_207_p2)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

h264_v_frmbuf_wr_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_done <= 1'b0;
        end else if ((grp_FrmbufWrHlsDataFlow_fu_154_ap_done == 1'b1)) begin
            ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready <= 1'b0;
        end else if ((grp_FrmbufWrHlsDataFlow_fu_154_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FrmbufWrHlsDataFlow_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_FrmbufWrHlsDataFlow_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_FrmbufWrHlsDataFlow_fu_154_ap_ready == 1'b1)) begin
            grp_FrmbufWrHlsDataFlow_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    s_axi_CTRL_flush_done <= m_axi_mm_video_flush_done;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        WidthInBytes_reg_238 <= WidthInBytes_fu_207_p2;
        colorFormat_reg_243 <= MEMORY2LIVE_q0;
        empty_reg_233 <= empty_fu_195_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_48_reg_218 <= empty_48_fu_185_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        empty_49_reg_263 <= empty_49_fu_213_p1;
        frm_buffer2_read_reg_248 <= frm_buffer2;
        frm_buffer_read_reg_253 <= frm_buffer;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        BYTES_PER_PIXEL_ce0 = 1'b1;
    end else begin
        BYTES_PER_PIXEL_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        MEMORY2LIVE_ce0 = 1'b1;
    end else begin
        MEMORY2LIVE_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_FrmbufWrHlsDataFlow_fu_154_ap_continue = 1'b1;
    end else begin
        grp_FrmbufWrHlsDataFlow_fu_154_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        mm_video_AWVALID = grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_AWVALID;
    end else begin
        mm_video_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        mm_video_BREADY = grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_BREADY;
    end else begin
        mm_video_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        mm_video_WVALID = grp_FrmbufWrHlsDataFlow_fu_154_m_axi_mm_video_WVALID;
    end else begin
        mm_video_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video_TREADY_int_regslice = grp_FrmbufWrHlsDataFlow_fu_154_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BYTES_PER_PIXEL_address0 = zext_ln151_fu_189_p1;

assign MEMORY2LIVE_address0 = zext_ln151_fu_189_p1;

assign WidthInBytes_fu_207_p0 = WidthInBytes_fu_207_p00;

assign WidthInBytes_fu_207_p00 = empty_fu_195_p1;

assign WidthInBytes_fu_207_p1 = WidthInBytes_fu_207_p10;

assign WidthInBytes_fu_207_p10 = BYTES_PER_PIXEL_q0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready & ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_done) == 1'b0);
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_done = (grp_FrmbufWrHlsDataFlow_fu_154_ap_done | ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_done);

assign ap_sync_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready = (grp_FrmbufWrHlsDataFlow_fu_154_ap_ready | ap_sync_reg_grp_FrmbufWrHlsDataFlow_fu_154_ap_ready);

assign empty_48_fu_185_p1 = video_format[5:0];

assign empty_49_fu_213_p1 = height[9:0];

assign empty_fu_195_p1 = width[10:0];

assign grp_FrmbufWrHlsDataFlow_fu_154_ap_start = grp_FrmbufWrHlsDataFlow_fu_154_ap_start_reg;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign zext_ln151_fu_189_p1 = video_format;


// synthesis translate_off
`include "h264_v_frmbuf_wr_0_0_hls_deadlock_detector.vh"
`include "h264_v_frmbuf_wr_0_0_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //h264_v_frmbuf_wr_0_0_v_frmbuf_wr

