# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Work/fpga/zynq_camera_vdma_lcd/.Xil/Vivado-21884-LEGION-BIANXINQUAN/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_blc.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_bnr.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_ccm.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_csc.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_demosaic.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_dgain.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_dpc.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_ee.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_gamma.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_stat_ae.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_stat_awb.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_top.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_utils.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/isp_lite/isp_wb.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/xil_isp_lite_v1_0_S00_AXI.v
      d:/Work/fpga/zynq_camera_vdma_lcd/xil_ip_repo/xil_isp_lite_1.0/hdl/xil_isp_lite_v1_0.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top xil_isp_lite_v1_0
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/Work/fpga/zynq_camera_vdma_lcd/.Xil/Vivado-21884-LEGION-BIANXINQUAN/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
